package com.persoff68.fatodo.model.constants;

public enum EventType {
    // ACCOUNT
    WELCOME,

    // CONTACT
    CONTACT_SEND,
    CONTACT_ACCEPT,

    // ITEM
    ITEM_CREATE,
    ITEM_UPDATE,
    ITEM_DELETE,
    ITEM_GROUP_CREATE,
    ITEM_GROUP_UPDATE,
    ITEM_MEMBER_ADD,
    ITEM_MEMBER_DELETE,
    ITEM_MEMBER_LEAVE,
    ITEM_MEMBER_ROLE,

    // COMMENT
    COMMENT_ADD,
    COMMENT_REACTION,

    // CHAT
    CHAT_CREATE,
    CHAT_UPDATE,
    CHAT_MEMBER_ADD,
    CHAT_MEMBER_DELETE,
    CHAT_MEMBER_LEAVE,
    CHAT_REACTION,

    // REMINDER
    REMINDER

}
